# Generated by Django 5.0.1 on 2024-02-06 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Overtimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('appointment_time', models.CharField(max_length=3)),
                ('meetings', models.IntegerField()),
                ('overtime', models.CharField(max_length=5)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
