# Generated by Django 5.0.1 on 2024-02-06 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimes',
            name='date',
            field=models.DateField(unique=True),
        ),
    ]
