# Generated by Django 5.0.1 on 2024-02-06 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0003_overtimes_districts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimes',
            name='districts',
            field=models.CharField(max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='overtimes',
            name='meetings',
            field=models.CharField(max_length=5),
        ),
    ]
