# Generated by Django 5.0.1 on 2024-02-06 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0004_alter_overtimes_districts_alter_overtimes_meetings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='overtimes',
            options={'ordering': ['-date']},
        ),
    ]
