# Generated by Django 5.0.1 on 2024-02-08 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0006_overtimes_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='overtimes',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
