# Generated by Django 5.0.1 on 2024-02-10 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0008_education_pharmacy_usefull_info'),
    ]

    operations = [
        migrations.AddField(
            model_name='education',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='pharmacy',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='usefull_info',
            name='user_id',
            field=models.IntegerField(null=True),
        ),
    ]
