# Generated by Django 5.0.1 on 2024-02-10 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('overtime', '0009_education_user_id_pharmacy_user_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pharmacy',
            name='photo',
            field=models.ImageField(upload_to='images'),
        ),
    ]
